# Generated by Django 2.0.6 on 2018-06-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a category', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pornstar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('rank', models.IntegerField()),
                ('bio', models.TextField()),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('category', models.ManyToManyField(to='info.Category')),
                ('pornstar', models.ManyToManyField(to='info.Pornstar')),
            ],
        ),
    ]
